name:                haskell-tree-sitter
version:             0.1.0.0
github:              "ervinoro/haskell-tree-sitter"
license:             ISC
author:              "Ervin Oro"
maintainer:          "ervin.oro@gmail.com"
copyright:           "2019 Ervin Oro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ervinoro/haskell-tree-sitter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-tree-sitter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tree-sitter

tests:
  haskell-tree-sitter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tree-sitter
