name:                haskell-tree-sitter
version:             0.1.0.0
github:              "ervinoro/haskell-tree-sitter"
license:             ISC
author:              "Ervin Oro"
maintainer:          "ervin.oro@gmail.com"
copyright:           "2019 Ervin Oro"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ervinoro/haskell-tree-sitter#readme>

dependencies:
- base >= 4.7 && < 5
- bindings-DSL

library:
  source-dirs: src
  exposed-modules: TreeSitter.Api
  include-dirs:
    - vendor/tree-sitter/lib/include/
    - vendor/tree-sitter/lib/src
    - vendor/tree-sitter/lib/utf8proc
    - includes/
  install-includes:
    - hs_api.h
    - tree_sitter/api.h
  c-sources:
    - src/hs_api.c
    - vendor/tree-sitter/lib/src/lib.c
  default-extensions:
    - ForeignFunctionInterface
